import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function renderReport(output){
 const markdown=await readFile(join(output,'notes/01-understanding.md'),'utf8');
 function inline(s){const tokens=[];const keep=v=>`\u0000${tokens.push(v)-1}\u0000`;s=s.replace(/`([^`]+)`/g,(_,v)=>keep(`<code>${esc(v)}</code>`));s=s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>{if(url==='../README.md')url='./';if(!/^(https:\/\/|\.\/|#)/.test(url))throw Error('Unsupported report link '+url);return keep(`<a href="${esc(url)}">${esc(label)}</a>`);});return esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\u0000(\d+)\u0000/g,(_,n)=>tokens[Number(n)]);}
 const lines=markdown.split(/\r?\n/),html=[],toc=[];
 for(let i=0;i<lines.length;){const s=lines[i];if(!s.trim()){i++;continue;}const h=s.match(/^(#{1,3}) (.+)$/);if(h){const level=h[1].length,id='section-'+i;html.push(`<h${level} id="${id}">${inline(h[2])}</h${level}>`);if(level===2)toc.push(`<a href="#${id}">${esc(h[2])}</a>`);i++;continue;}if(s.startsWith('|')){const rows=[];while(i<lines.length&&lines[i].startsWith('|'))rows.push(lines[i++]);const cells=r=>r.slice(1,r.lastIndexOf('|')).split('|').map(v=>inline(v.trim()));html.push('<div class="table-scroll" tabindex="0" role="region" aria-label="研究对照表"><table><thead><tr>'+cells(rows[0]).map(v=>`<th scope="col">${v}</th>`).join('')+'</tr></thead><tbody>'+rows.slice(2).map(r=>'<tr>'+cells(r).map(v=>`<td>${v}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>');continue;}if(/^(- |\d+\. )/.test(s)){const ordered=/^\d/.test(s),items=[];while(i<lines.length&&(ordered?/^\d+\. /:/^- /).test(lines[i]))items.push('<li>'+inline(lines[i++].replace(/^(- |\d+\. )/,''))+'</li>');html.push(`<${ordered?'ol':'ul'}>${items.join('')}</${ordered?'ol':'ul'}>`);continue;}const p=[];while(i<lines.length&&lines[i].trim()&&!/^(#{1,3} |\||- |\d+\. )/.test(lines[i]))p.push(inline(lines[i++]));html.push('<p>'+p.join(' ')+'</p>');}
 await writeFile(join(output,'understanding.html'),`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Pi Web 完整理解：能力、本质、与 Codex 对比的意义、运行机制和扩展边界。"><title>完整理解 · Pi Web</title><link rel="stylesheet" href="style.css"></head><body class="report"><header><a href="./">← 返回 Pi Web 展示</a><a href="notes/01-understanding.md" download>下载完整 Markdown</a></header><main><nav class="report-toc" aria-label="研究目录">${toc.join('')}</nav><article>${html.join('\n')}</article><figure><a href="assets/research-overview.svg"><img src="assets/research-overview.png" alt="Pi Web 完整理解总览：技术分工、Codex 对比、六类能力与扩展边界" width="1800" height="2210"></a><figcaption>本研究原创总览，依据文中固定源码与官方资料，非产品截图。点击放大 SVG。</figcaption></figure></main><footer><a href="./">返回项目展示</a><a href="../">演示导航</a></footer></body></html>`);
}
