import {cp,mkdir,readFile,writeFile,realpath,lstat,rm} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {render,escape} from './render.mjs';
const web=await realpath(fileURLToPath(new URL('../',import.meta.url))),project=dirname(web),out=resolve(web,'dist');
if(dirname(out)!==web)throw new Error('Output escaped project');
try{const item=await lstat(out);if(item.isSymbolicLink()||await realpath(out)!==out)throw new Error('Redirected output');await rm(out,{recursive:true});}catch(e){if(e.code!=='ENOENT')throw e;}
await mkdir(out);await cp(join(web,'public'),out,{recursive:true});await mkdir(join(out,'assets'));await mkdir(join(out,'notes'));
for(const file of ['entry-guide.svg','entry-guide.png','full-architecture.svg','full-architecture.png','full-architecture.mmd'])await cp(join(project,'assets',file),join(out,'assets',file));
const repo='https://github.com/yydshly/0910_codex_project/tree/main/projects/011-luvus';
function page(title,content){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Luvus 是多 Agent 终端工作台，统一接入 Claude Code、Codex、Pi 等编程助手，支持任务下发与依赖管理、会话恢复、状态跟踪、并行工作目录协调、检查命令和分支整合，并提供远程接入、定时任务与模块扩展。"><title>${escape(title)} · Luvus 研究</title><link rel="stylesheet" href="./style.css"></head><body><div class="shell"><header class="topbar"><a class="brand" href="./">011 / LUVUS</a><nav aria-label="项目导航"><a href="./understanding.html">完整理解</a><a href="./architecture.html">详细架构</a><a href="./sources.html">来源与验证</a><a href="../">研究导航</a></nav></header>${content}<footer><a href="${repo}">GitHub 研究文档 ↗</a><span>原创中文整理 · 固定版本 0.13.4 · 上游未运行验证</span><a href="https://github.com/RizRiyz/luvus">上游仓库 ↗</a></footer></div></body></html>\n`;}
const intro=`<main id="guide"><p class="eyebrow">任务管理 ＋ AGENT 适配</p><h1>统一管理 Agent、任务与会话。</h1><p class="intro">Luvus 是多 Agent 终端工作台，统一接入 Claude Code、Codex、Pi 等编程助手，支持任务下发与依赖管理、会话恢复、状态跟踪、并行工作目录协调、检查命令和分支整合，并提供远程接入、定时任务与模块扩展。</p><figure class="guide"><a href="./assets/entry-guide.svg"><img src="./assets/entry-guide.svg" alt="任务来源进入 Luvus 的任务管理和 Agent 适配，连接已有助手执行并返回结果" width="1200" height="850"></a><figcaption>模块引导图 · 本研究依据固定源码原创绘制，非产品截图。<a href="./assets/entry-guide.svg">放大查看</a> · <a href="./assets/entry-guide.png" download>下载图片</a></figcaption></figure><section class="module-grid" aria-label="三个模块"><article><span class="number">01 / 管理工作</span><h2>任务管理</h2><p>下发任务、跟踪状态、管理依赖，协调工作目录，再检查和整合结果。</p><a href="./understanding.html#section-2">看任务如何推进 →</a></article><article><span class="number">02 / 连接工具</span><h2>Agent 适配</h2><p>统一识别、启动、输入、输出及支持的会话操作，保留各工具自身的执行方式。</p><a href="./understanding.html#section-3">看适配哪些能力 →</a></article><article><span class="number">03 / 完成任务</span><h2>已有 Agent 执行</h2><p>助手调用模型、读写文件和运行命令；可由人管理、主 Agent 统筹或彼此交接。</p><a href="./understanding.html#section-4">看主 Agent 是否必要 →</a></article></section><section class="reading" id="reading"><h2>沿着模块，继续理解</h2><a href="./understanding.html"><strong>完整理解：能力、原理与对我们的意义</strong><span>九节中文整理，覆盖直接指令、正式任务、会话、多 Agent、适用场景和扩展方向。</span></a><a href="./understanding.html#section-6"><strong>与 Multica、MetaGPT 的差异</strong><span>Luvus 偏执行现场；Multica 偏长期任务协作；MetaGPT 偏框架内角色与流程。</span></a><a href="./architecture.html"><strong>展开上一层详细架构</strong><span>保留七组模块的详细总览、读图说明与原始 Mermaid 图。</span></a></section><p class="note">后台服务负责控制机制；主 Agent 负责可选的规划与判断。状态结束、检查通过与业务验收是不同层次。</p><div class="downloads"><a href="./notes/01-understanding.md" download>下载完整理解</a><a href="./sources.html">查看来源与验证范围</a></div></main>`;
await writeFile(join(out,'index.html'),page('模块引导',intro));
for(const [name,slug] of [['01-understanding.md','understanding'],['02-full-architecture.md','architecture'],['03-sources-and-verification.md','sources']]){
 const md=await readFile(join(project,'notes',name),'utf8'),title=md.match(/^# (.+)$/m)[1],article=render(md);
 await cp(join(project,'notes',name),join(out,'notes',name));
 await writeFile(join(out,slug+'.html'),page(title,`<main class="article"><p class="eyebrow"><a href="./">← 返回模块引导</a></p><h1>${escape(title)}</h1><nav class="toc" aria-label="文章目录">${article.toc}</nav>${article.body}<div class="downloads"><a href="./notes/${name}" download>下载本文 Markdown</a><a href="./">返回模块引导</a></div></main>`));
}
console.log('Luvus: four reading pages, two diagrams and matching research downloads built.');
