import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createGame,stepGame,action,MODES,DT,holes,racePaths} from '../public/games-engine.mjs';
import {registerGameDirection} from '../public/games-webmcp.mjs';
const tick=(g,seconds,input={})=>{for(let i=0;i<Math.round(seconds/DT);i++)stepGame(g,DT,input);return g;};
const finish=g=>{for(let i=0;i<36000&&!['won','lost'].includes(g.status);i++)stepGame(g,DT);return g;};
assert.equal(new Set(MODES.map(m=>m.id)).size,8);
for(const m of MODES){const g=finish(createGame(m.id,true));assert.equal(g.status,'won',m.id+' demonstration must reach its real goal');assert(g.time<120,m.id+' bounded demo');const time=g.time,score=g.score;tick(g,2);assert.equal(g.time,time,'Finished time stays fixed');assert.equal(g.score,score,'No duplicate scoring after completion');console.log(`${m.id}: completed in ${g.time.toFixed(2)} simulation seconds.`);}
const puzzle=createGame('puzzle',false);tick(puzzle,35);assert.equal(puzzle.status,'ready');action(puzzle,'launch');assert.equal(finish(puzzle).status,'won','Waiting before launch must not trigger stale timeout');action(puzzle,'angle',500);assert.equal(puzzle.angle,42);action(puzzle,'launch');assert.equal(puzzle.attempts,2);
const maze=createGame('maze',false);tick(maze,.4,{x:1});assert(maze.b.x>110,'User tilt changes movement');maze.b.x=holes[0].x;maze.b.y=holes[0].y;stepGame(maze,DT);assert.equal(maze.status,'lost','Black hole causes failure');
const breakout=createGame('breakout',false);tick(breakout,.5,{pointerX:600});assert.equal(breakout.paddle,600);breakout.lives=1;breakout.b.y=590;stepGame(breakout,DT);assert.equal(breakout.status,'lost','Final miss ends run');
const track=createGame('track',false);action(track,'launch');stepGame(track,DT);assert.equal(track.status,'lost','Broken entrance is rejected');action(track,'solve');action(track,'launch');const rotation=track.tiles[0].rotation;action(track,'rotate',0);assert.equal(track.tiles[0].rotation,rotation,'Cannot mutate a running track');assert.equal(finish(track).status,'won','User can solve and test');action(track,'rotate',0);action(track,'launch');stepGame(track,DT);assert.equal(track.status,'lost');
const chain=createGame('chain',false);action(chain,'delay',1.2);action(chain,'launch');assert.equal(finish(chain).status,'lost','Late opening causes actual gate collision');action(chain,'delay',.2);action(chain,'launch');assert.equal(finish(chain).status,'won','Changing delay repairs run');
const sorting=createGame('sorting',false);action(sorting,'select',0);finish(sorting);assert.equal(sorting.score,4);assert.equal(sorting.status,'lost','Wrong classification cannot pass');const locked=createGame('sorting',false);tick(locked,2.1);const first=locked.balls[0];assert.equal(first.route,1);action(locked,'select',2);tick(locked,.1);assert.equal(first.route,1,'Route locks at junction');
const rhythm=createGame('rhythm',false);tick(rhythm,1.8);action(rhythm,'hit',0);assert.equal(rhythm.score,100);action(rhythm,'hit',0);assert.equal(rhythm.score,100,'One note cannot score twice');finish(rhythm);assert.equal(rhythm.status,'lost','Missed notes affect result');assert.equal(rhythm.bestCombo,1);
const race=createGame('race',false);tick(race,1,{boost:true});assert(race.energy<100);const spent=race.energy;tick(race,1,{boost:false});assert(race.energy>spent,'Energy regenerates');assert(racePaths.short.length<racePaths.outer.length);const slow=finish(createGame('race',false));assert(slow.rank>1,'No acceleration loses to opponents');for(const route of ['short','outer']){const test=createGame('race',false);action(test,'route',route);for(let i=0;i<5000&&test.status==='playing';i++){stepGame(test,DT,{boost:true});assert(test.energy>=0&&test.energy<=100);assert(Number.isFinite(test.progress));}}
let tool,calls=0;const cleanup=registerGameDirection({registerTool(value){tool=value;}},input=>{calls++;return input;});assert.equal(tool.name,'start_game_direction');assert.deepEqual(tool.execute({game:'maze',autoplay:false}),{game:'maze',autoplay:false});for(const bad of [null,[],{game:'bad',autoplay:true},{game:'race',autoplay:'yes'},{game:'race',autoplay:true,extra:1}])assert.throws(()=>tool.execute(bad));assert.equal(calls,1);cleanup();
const html=await readFile(new URL('../public/games.html',import.meta.url),'utf8'),app=await readFile(new URL('../public/games-app.mjs',import.meta.url),'utf8');const ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));for(const [,id]of app.matchAll(/\$\('([^']+)'\)/g))assert(ids.has(id),'Missing UI target '+id);
console.log('Eight real goal paths, failure/retry cases, input effects, timing, energy, route locks, DOM references and optional tool contract passed. Browser UI and live WebMCP not tested.');
