import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createGame,stepGame,action,MODES,DT,holes,racePaths,progress,rating} from '../public/games-engine.mjs';
import {drawGame} from '../public/games-view.mjs';
import {registerGameDirection} from '../public/games-webmcp.mjs';
const tick=(g,seconds,input={})=>{for(let i=0;i<Math.round(seconds/DT);i++)stepGame(g,DT,input);return g;};
const finish=(g,input={})=>{for(let i=0;i<24000&&!['won','lost'].includes(g.status);i++)stepGame(g,DT,input);return g;};
// Check drawing contracts without a browser: reject non-finite geometry at representative states.
const geometry=new Set(['setTransform','clearRect','fillRect','translate','scale','moveTo','lineTo','rect','roundRect','arc','strokeRect','quadraticCurveTo','bezierCurveTo']);
const ctx=new Proxy({}, {get(target,key){if(key in target)return target[key];if(key==='createRadialGradient')return (...args)=>{assert(args.every(Number.isFinite));return {addColorStop(){}};};return (...args)=>{if(geometry.has(key))assert(args.every(a=>typeof a==='boolean'||Number.isFinite(a)),'Finite drawing geometry: '+key);};},set(t,k,v){t[k]=v;return true;}});
assert.equal(new Set(MODES.map(m=>m.id)).size,8);
for(const level of [1,2,3])for(const m of MODES){
 const g=createGame(m.id,true,level);drawGame(ctx,g,900,560);tick(g,1);drawGame(ctx,g,390,303,2);tick(g,2);drawGame(ctx,g,900,560);finish(g);drawGame(ctx,g,900,560);
 assert.equal(g.status,'won',level+' '+m.id+' demonstration must reach its real goal');assert(g.time<120,m.id+' bounded demonstration');assert.equal(progress(g),1);assert(rating(g)>0);
 const time=g.time,score=g.score;tick(g,2);assert.equal(g.time,time);assert.equal(g.score,score);console.log(`${level} / ${m.id}: won in ${g.time.toFixed(2)} simulation seconds.`);
}
const puzzle=createGame('puzzle',false,1);tick(puzzle,35);assert.equal(puzzle.status,'ready');action(puzzle,'launch');action(puzzle,'angle',40);assert.equal(puzzle.angle,22,'Flight locks parameters');assert.equal(finish(puzzle).status,'won');action(puzzle,'angle',500);assert.equal(puzzle.angle,42);action(puzzle,'launch');assert.equal(puzzle.attempts,2);assert(puzzle.ghost.length>0);assert.equal(puzzle.score,0);finish(puzzle);puzzle.attempts=puzzle.maxAttempts;action(puzzle,'launch');assert.notEqual(puzzle.status,'playing','Attempt budget enforced');
const unsolved=createGame('puzzle',false);action(unsolved,'launch');assert.equal(finish(unsolved).status,'lost','Manual challenge requires adjusting the setup');
const missingStar=createGame('puzzle',false,1);action(missingStar,'launch');missingStar.stars[0].x=-100;finish(missingStar);assert.equal(missingStar.status,'lost','Entering cup without all stars fails');
const maze=createGame('maze',false);tick(maze,.4,{x:1});assert(maze.b.x>110);maze.b.x=maze.keys[0].x;maze.b.y=maze.keys[0].y;maze.b.vx=0;stepGame(maze,DT);assert.equal(maze.score,1);maze.b.x=holes[0].x;maze.b.y=holes[0].y;stepGame(maze,DT);assert.equal(maze.status,'playing');assert.equal(maze.rescues,0);assert.equal(maze.b.x,maze.checkpoint.x);maze.b.x=holes[0].x;maze.b.y=holes[0].y;stepGame(maze,DT);assert.equal(maze.status,'lost');
const brake=createGame('maze',false),coast=createGame('maze',false);brake.b.vx=100;coast.b.vx=100;tick(brake,.3,{brake:true});tick(coast,.3);assert(brake.b.vx<coast.b.vx*.4,'Brake reduces inertia');const lockedExit=createGame('maze',false);lockedExit.b.x=800;lockedExit.b.y=450;stepGame(lockedExit,DT);assert.equal(lockedExit.status,'playing','Keys required at exit');lockedExit.time=lockedExit.timeLimit;stepGame(lockedExit,DT);assert.equal(lockedExit.status,'lost','Maze timeout');
const breakout=createGame('breakout',false);tick(breakout,.5,{pointerX:600});assert.equal(breakout.paddle,600);breakout.lives=1;breakout.b.y=590;stepGame(breakout,DT);assert.equal(breakout.status,'lost');
const armor=createGame('breakout',false,3),brick=armor.bricks[0];armor.b.x=brick.x+brick.w/2;armor.b.y=brick.y+32;armor.b.vx=0;armor.b.vy=-100;stepGame(armor,DT);assert.equal(brick.hp,2);assert(brick.alive,'Armored brick survives first hit');action(armor,'pulse');assert.equal(armor.charges,1);assert.equal(brick.hp,1);action(armor,'pulse');assert(!brick.alive);const spent=armor.score;action(armor,'pulse');assert.equal(armor.score,spent,'No unlimited pulses');
const power=createGame('breakout',false);power.drops=[{x:450,y:478,kind:'wide'}];stepGame(power,DT);assert(power.wideUntil>9);power.drops=[{x:450,y:478,kind:'pierce'}];stepGame(power,DT);assert(power.pierceUntil>7);tick(power,11,{pointerX:450});assert(power.time>power.wideUntil||power.status==='lost','Power duration is bounded');
const track=createGame('track',false);const lock=track.tiles[4].rotation;action(track,'rotate',4);assert.equal(track.tiles[4].rotation,lock);assert.equal(track.moves,0);action(track,'rotate',0);action(track,'undo');assert.equal(track.moves,0);for(let i=0;i<track.budget;i++)action(track,'rotate',0);const before=track.tiles[0].rotation;action(track,'rotate',0);assert.equal(track.tiles[0].rotation,before);action(track,'undo');assert.equal(track.moves,track.budget-1);
const broken=createGame('track',false);action(broken,'launch');stepGame(broken,DT);assert.equal(broken.status,'lost');action(broken,'solve');action(broken,'launch');const rotation=broken.tiles[0].rotation;action(broken,'rotate',0);action(broken,'solve');assert.equal(broken.status,'playing','No route replacement mid-run');assert.equal(broken.tiles[0].rotation,rotation);assert.equal(finish(broken).status,'won');assert.equal(rating(broken),1,'Assisted rating is capped');
const hint=createGame('track',false);action(hint,'hint');assert.equal(hint.moves,1);assert(hint.assisted);
for(const delay of [0,1.2]){const chain=createGame('chain',false,3);for(let i=0;i<3;i++)action(chain,'gateDelay',{index:i,delay});action(chain,'launch');assert.equal(finish(chain).status,'lost','Early and late windows both fail');}
const chain=createGame('chain',false,3);for(const [i,s]of chain.switches.entries())action(chain,'gateDelay',{index:i,delay:(s.gate-s.x)/chain.launchSpeed-chain.gateWindow/2});action(chain,'launch');assert.equal(finish(chain).status,'won');assert(chain.switches.every(s=>s.passed));
const sorting=createGame('sorting',false);finish(sorting);assert.equal(sorting.status,'lost');assert.equal(sorting.lives,0);const sorted=createGame('sorting',true);while(sorted.wave===1)stepGame(sorted,DT);assert.deepEqual(sorted.bins,[1,2,0]);assert.equal(sorted.balls.length,0,'Bins rotate only after wave clears');assert.equal(sorted.resolved,8);finish(sorted);assert.equal(sorted.score,24);assert.equal(sorted.bestCombo,24);
const locked=createGame('sorting',false);tick(locked,2.5);const first=locked.balls[0];assert.equal(first.route,1);action(locked,'select',2);tick(locked,.1);assert.equal(first.route,1,'Route locks at junction');
const rhythm=createGame('rhythm',false);tick(rhythm,1.8);action(rhythm,'hit',0);assert.equal(rhythm.score,100);action(rhythm,'hit',0);assert.equal(rhythm.score,75,'Repeated empty hits penalized');finish(rhythm);assert.equal(rhythm.status,'lost');assert.equal(rhythm.ghosts,1);
const held=createGame('rhythm',false),note=held.notes.find(n=>n.duration);held.time=note.at;action(held,'hit',note.lane);assert.equal(note.state,'holding');action(held,'release',note.lane);assert.equal(note.state,'miss','Early release fails hold');
const sustained=createGame('rhythm',false),hold=sustained.notes.find(n=>n.duration);sustained.time=hold.at;action(sustained,'hit',hold.lane);tick(sustained,hold.duration);assert.equal(hold.state,'hit');assert.equal(sustained.score,150,'Sustained note awards completion bonus');
const chord=createGame('rhythm',false),pair=chord.notes.filter(n=>n.at===chord.notes[7].at);assert.equal(pair.length,2);chord.time=pair[0].at;pair.forEach(n=>action(chord,'hit',n.lane));assert(pair.every(n=>n.state==='hit'));
assert(racePaths.short.length<racePaths.outer.length);for(const route of ['short','outer']){const smart=createGame('race',true);action(smart,'route',route);finish(smart);assert.equal(smart.status,'won',route+' is viable with timing');assert.equal(smart.lap,3);assert.equal(smart.recharges,3);assert.equal(smart.spins,0);const slow=createGame('race',false);action(slow,'route',route);finish(slow);assert(slow.rank>1);}
const reckless=createGame('race',false);finish(reckless,{boost:true});assert(reckless.spins>0);assert.equal(reckless.status,'lost','Holding boost throughout loses on challenge difficulty');const race=createGame('race',false);tick(race,1,{boost:true});const energy=race.energy;tick(race,.5);assert(race.energy>energy);assert(race.energy>=0&&race.energy<=100);
let tool,calls=0;const cleanup=registerGameDirection({registerTool(value){tool=value;}},input=>{calls++;return input;});assert.equal(tool.name,'start_game_direction');assert.deepEqual(tool.execute({game:'maze',autoplay:false}),{game:'maze',autoplay:false});for(const bad of [null,[],{game:'bad',autoplay:true},{game:'race',autoplay:'yes'},{game:'race',autoplay:true,extra:1}])assert.throws(()=>tool.execute(bad));assert.equal(calls,1);cleanup();
const html=await readFile(new URL('../public/games.html',import.meta.url),'utf8'),app=await readFile(new URL('../public/games-app.mjs',import.meta.url),'utf8');const ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));for(const [,id]of app.matchAll(/\$\('([^']+)'\)/g))assert(ids.has(id),'Missing UI target '+id);
console.log('24 goal paths, strategy tradeoffs, failure/retry, drawing geometry, UI references and optional tool contract passed. No browser, real audio or live WebMCP test.');
