import {readFile,writeFile,mkdir,cp,realpath,lstat,rm} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const web=await realpath(fileURLToPath(new URL('../',import.meta.url))),project=dirname(web),out=resolve(web,'dist');
if(dirname(out)!==web)throw new Error('Output escaped project');
try{const item=await lstat(out);if(item.isSymbolicLink()||await realpath(out)!==out)throw new Error('Redirected output');await rm(out,{recursive:true});}catch(e){if(e.code!=='ENOENT')throw e;}
await mkdir(out);await cp(join(web,'public'),out,{recursive:true});await cp(join(web,'data'),join(out,'data'),{recursive:true});await mkdir(join(out,'assets'));await cp(join(project,'assets/capability-overview.svg'),join(out,'assets/capability-overview.svg'));await cp(join(project,'notes'),join(out,'notes'),{recursive:true});
const read=async name=>JSON.parse(await readFile(join(web,'data',name),'utf8'));
const [lessons,inventory,guides,terms]=await Promise.all(['lessons.json','source-inventory.json','section-guides.json','glossary.json'].map(read));
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sha=inventory.sha,upstream='https://github.com/crypto101/book/blob/'+sha+'/',repo='https://github.com/yydshly/0910_codex_project/tree/main/projects/012-crypto101-book';
const sourceLink=(file,line)=>upstream+file+(line?'#L'+line:'');
const groups=[...new Set(lessons.map(l=>l.group))];
const totalHeadings=inventory.chapters.reduce((n,c)=>n+c.sections.length,0),todoSections=inventory.chapters.flatMap(c=>c.sections).filter(s=>s.todoLines.length).length;
const nav=(current)=>groups.map(g=>'<h2>'+esc(g)+'</h2>'+lessons.filter(l=>l.group===g).map(l=>'<a data-chapter="'+l.id+'" href="./'+l.id+'.html"'+(current===l.id?' aria-current="page"':'')+'><span class="navnum">'+String(l.order).padStart(2,'0')+'</span>'+esc(l.title)+'<span class="done"></span></a>').join('')).join('');
function page(title,body,current=''){return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Crypto 101 中文学习导读：全部章节目录、学习目标、概念、原文定位、自检与个人进度。"><title>'+esc(title)+' · Crypto 101 学习指南</title><link rel="stylesheet" href="./style.css"></head><body data-lesson="'+current+'"><a class="skip" href="#main">跳到正文</a><header class="topbar"><a class="brand" href="./">012 / CRYPTO 101</a><nav aria-label="站点导航"><a href="./">学习地图</a><a href="./glossary.html">术语对照</a><a href="./sources.html">来源与范围</a><a href="../">项目导航</a></nav></header><div class="layout"><aside class="sidebar"><button type="button" class="toc-toggle secondary" data-toggle-toc aria-expanded="false" aria-controls="course-nav">展开或收起学习目录</button><div class="progress"><div data-progress>18 个学习单元</div><progress value="0" max="18" aria-label="个人自评学习进度"></progress></div><nav class="course-nav" id="course-nav" aria-label="课程目录">'+nav(current)+'</nav></aside><main class="content" id="main">'+body+'</main></div><footer class="footer">依据 Crypto 101 / Laurens Van Houtven 及贡献者 · <a href="'+upstream+'LICENSE">上游 CC BY-NC 4.0</a> · 固定版本 '+sha.slice(0,7)+' · 中文原创导读，非完整译本<br>本站构建与上游电子书、密码学实验分别验证。<a href="'+repo+'">研究文档</a> · <a href="./sources.html">核对来源与未完成内容</a></footer><script type="module" src="./app.mjs"></script></body></html>\n';}
const cards=groups.map(g=>'<section><h2>'+esc(g)+'</h2><div class="chapter-grid">'+lessons.filter(l=>l.group===g).map(l=>'<a class="chapter-card" href="./'+l.id+'.html"><span class="eyebrow">单元 '+String(l.order).padStart(2,'0')+'</span><h3>'+esc(l.title)+'</h3><p>'+esc(l.question)+'</p><span class="meta">'+esc(l.goals[0])+' →</span></a>').join('')+'</div></section>').join('');
const home='<p class="eyebrow">中文学习地图</p><h1>从一个问题，理解一套安全系统。</h1><p class="lead">逐章认识加密、认证与密钥，读懂漏洞为何发生，再把它们放回 TLS、GPG 和 OTR。先读目标和例子，回答自检，再带着疑问深入原文。</p><div class="intro-grid"><section class="panel dark"><h2>从这里开始</h2><p>已有 '+lessons.length+' 个学习单元。第一次学习从目标与 XOR 出发；以后按照你的个人进度继续。</p><a class="button" data-resume href="./foreword.html">从学习目标开始 →</a><p class="small">完成标记和笔记仅保存在当前浏览器，不会上传。自评完成不代表自动通过考试。</p></section><section class="panel"><h2>每一章怎样学</h2><ol><li>读目标，说明自己要解决的问题。</li><li>看概念与例子，解释每个条件。</li><li>回答自检题，再展开参考思路。</li><li>记下疑问，复制引导语让我陪你继续。</li></ol></section></div><p class="notice">完整覆盖原书 '+totalHeadings+' 个标题的学习入口，含 '+terms.length+' 个术语和 '+inventory.references.length+' 条参考文献索引。部分原文只有标题或 TODO，已单独标识；本站不把空白章节包装成完整教材。</p>'+cards+'<section id="guide"><h2>把各部分联系起来</h2><figure class="figure"><a href="./assets/capability-overview.svg"><img src="./assets/capability-overview.svg" width="1280" height="880" alt="基础组件、漏洞案例与完整系统的关系，下方列出书稿构建和验证边界"></a><figcaption>本研究原创图，依据固定书稿整理；不是运行截图。<a href="./assets/capability-overview.svg">打开原图</a></figcaption></figure><div class="actions"><a class="button secondary" href="./study-guide.md" download>下载完整中文导读</a><a href="./sources.html">查看证据与内容缺口</a></div></section>';
await writeFile(join(out,'index.html'),page('学习地图',home));
let markdown='# Crypto 101 中文学习导读\n\n原作：Laurens Van Houtven 及贡献者；CC BY-NC 4.0。固定版本 '+sha+'。本站原创学习解释与问题，不是完整译本。\n\n';
for(const lesson of lessons){
 const c=inventory.chapters.find(c=>c.id===lesson.id),sectionGuides=(guides[lesson.id]||'').split('\n').filter(Boolean).map(s=>{const [title,...body]=s.split('|');return {title,body:body.join('|')};});
 if(c&&sectionGuides.length!==c.sections.length-1)throw new Error('Guide coverage mismatch '+lesson.id);
 const clean=title=>title.replace(/:math:`([^`]+)`/g,'$1').replaceAll('`','');
 let sections=c?c.sections.slice(1).map((s,i)=>{const g=sectionGuides[i];return '<details class="topic" id="topic-'+s.line+'"'+(i===0?' open':'')+'><summary>'+esc(g.title)+' <span class="badge'+(s.status!=='原文有讲解'?' warn':'')+'">'+esc(s.status)+'</span><span class="en">'+esc(clean(s.title))+'</span></summary><div class="body"><p><strong>本站导读与学习目标：</strong>'+esc(g.body)+'</p><a class="source" href="'+sourceLink('src/'+lesson.id+'.rst',s.line)+'">定位原书第 '+s.line+' 行 ↗</a>'+(s.todoLines.length?'<p class="small muted">本段还包含待补说明。原文位置：'+s.todoLines.map(n=>'<a href="'+sourceLink('src/'+lesson.id+'.rst',n)+'">L'+n+'</a>').join('、')+'。</p>':'')+'</div></details>';}).join(''):'';
 if(lesson.id==='glossary'){sections='<dl class="glossary">'+inventory.terms.map(t=>{const guide=terms.find(x=>x.term===t.term);if(!guide)throw new Error('Missing glossary guide '+t.term);return '<div class="term" id="term-'+t.line+'"><dt>'+esc(t.term)+'</dt><dd>'+esc(guide.guide)+' <a class="small" href="'+sourceLink('src/glossary.rst',t.line)+'">原文 ↗</a></dd></div>';}).join('')+'</dl>';}
 if(lesson.id==='zreferences'){sections='<p>全部 '+inventory.references.length+' 条书目记录。标识来自原书，点击可查看相应 BibTeX 条目的作者、题名和网址；本站未逐篇核查结论。</p><ol>'+inventory.references.map(r=>'<li><a href="'+sourceLink('src/Crypto101.bib',r.line)+'">'+esc(r.key)+'</a> <span class="muted">'+esc(r.kind)+'</span></li>').join('')+'</ol>';}
 if(lesson.id==='book-engineering'){sections='<div class="table-wrap"><table><thead><tr><th>材料</th><th>职责与阅读目标</th><th>来源</th></tr></thead><tbody>'+[['src/index.rst','章节、附录、术语与参考资料的总入口'],['src/conf.py','Sphinx 扩展、语言、排版与输出配置'],['Makefile','book 目标连接 html、latexpdf、epub'],['make-lang','语言参数影响构建配置，不生成译文'],['docker/Dockerfile.ubuntu','依赖环境；未实际构建'],['LICENSE','核对作者署名与非商业许可']].map(([file,goal])=>'<tr><td>'+esc(file)+'</td><td>'+goal+'</td><td><a href="'+sourceLink(file)+'">固定来源</a></td></tr>').join('')+'</tbody></table></div>';}
 const lab=lesson.id==='exclusive-or'?'<form class="lab" data-lab="xor"><h3>动手：同一个密钥异或两次</h3><p class="small">8 位玩具示例，只演示位运算。</p><label>明文（8 位）<input name="a" value="00101101" pattern="[01]{8}" maxlength="8" required></label><label>密钥（8 位）<input name="k" value="10101010" pattern="[01]{8}" maxlength="8" required></label><button type="submit">计算并恢复</button><output aria-live="polite">启用 JavaScript 后可演算。</output></form>':lesson.id==='key-exchange'?'<form class="lab" data-lab="dh"><h3>动手：双方怎样得到同一个值</h3><p class="small">固定 p=23，g=5；教学小参数，不产生真实安全密钥。</p><label>Alice 秘密数 a<input name="a" type="number" value="6" min="1" max="20" step="1" required></label><label>Bob 秘密数 b<input name="b" type="number" value="15" min="1" max="20" step="1" required></label><button type="submit">计算交换结果</button><output aria-live="polite">启用 JavaScript 后可演算。</output></form>':'';
 const prompt='请按 Crypto 101 中文学习指南，带我学习「'+lesson.title+'」。\n依据固定版本 '+sha+'，把上游已写内容、空白/TODO 与你补充的解释分开。\n先围绕“'+lesson.question+'”确认我的基础，再一次只讲一个概念，给一个小例子，然后问一道理解题。等我回答后纠正误区，再推进下一步。\n本章目标：'+lesson.goals.join('；')+'。\n不要把历史案例当作当前配置建议；需要补充最新知识时查权威来源。';
 const previous=lessons[lesson.order-1],next=lessons[lesson.order+1];
 const body='<p class="eyebrow">'+esc(lesson.group)+' / 单元 '+String(lesson.order).padStart(2,'0')+'</p><h1>'+esc(lesson.title)+'</h1><p class="lead">'+esc(lesson.question)+'</p><p class="meta">'+(c?'<a href="'+sourceLink('src/'+lesson.id+'.rst')+'">原书章节 ↗</a> · '+c.sections.length+' 个原始标题':'书稿工程补充单元')+' · <a href="./sources.html">版本与验证范围</a></p><section class="goals"><h2>学完后，你应该能</h2><ul>'+lesson.goals.map(g=>'<li>'+esc(g)+'</li>').join('')+'</ul></section><nav class="reading-nav" aria-label="本章目录"><a href="#concepts">核心概念</a><a href="#details">全部细节入口</a><a href="#check">自我检查</a><a href="#continue">保存疑问与继续学习</a></nav><section id="concepts"><h2>先建立理解</h2>'+lesson.concepts.map(c=>'<article class="concept"><h3>'+esc(c.title)+'</h3><p>'+esc(c.body)+'</p></article>').join('')+'<div class="example"><h3>用一个例子想一想</h3><p>'+esc(lesson.example)+'</p></div>'+lab+'</section><p class="notice">'+esc(lesson.limit)+'</p><section id="details"><h2>'+(lesson.id==='glossary'?'原书全部术语':lesson.id==='zreferences'?'原书全部参考文献入口':'逐项阅读与学习目标')+'</h2><p class="muted">中文段落是本站导读；原文内容状态与固定来源分开列出。无 TODO 标记不等于已完成技术审校。</p>'+(c&&c.sections.length>1?'<div class="actions"><button class="secondary" type="button" data-expand="open">展开全部细节</button><button class="secondary" type="button" data-expand="close">收起全部细节</button></div>':'')+'<div class="details-list">'+sections+'</div></section><section id="check"><h2>自我检查</h2><div class="quiz"><h3>'+esc(lesson.quiz.question)+'</h3><p class="muted">先用自己的话回答，再展开思路。能复述答案与能解释条件是不同阶段。</p><details><summary>查看参考思路</summary><p class="answer">'+esc(lesson.quiz.answer)+'</p></details></div><p>再做一步：为本章选一个概念，说出它解决的问题、依赖的条件，以及仍没有解决的问题。</p></section><section id="continue" class="study-controls"><h2>留下理解，下次接着学</h2><label for="study-note">我的理解与疑问（仅此浏览器保存）</label><textarea id="study-note" class="study-note" data-note maxlength="12000" placeholder="我目前能解释……；我还不明白……"></textarea><div class="actions"><button type="button" data-complete aria-pressed="false">我能回答自检题，标记完成</button></div><label for="guide-prompt">把这段引导语发给助手，逐步学习本章</label><textarea id="guide-prompt" class="guide-prompt" data-prompt readonly>'+esc(prompt)+'</textarea><div class="actions"><button class="secondary" type="button" data-copy>复制引导语与我的疑问</button></div><p class="status" data-save-status role="status"></p><p class="small muted">不同设备或浏览器不自动同步。清理浏览器数据会清除这些记录；按钮只复制文字，不会自动发送给助手。</p><noscript><p class="notice">当前 JavaScript 未启用，正文、目录和参考答案仍可阅读；进度、笔记保存与演算不可用。可手动复制上方引导语。</p></noscript></section><nav class="pager" aria-label="前后章节">'+(previous?'<a href="./'+previous.id+'.html">← '+esc(previous.title)+'</a>':'<a href="./">← 学习地图</a>')+(next?'<a href="./'+next.id+'.html">'+esc(next.title)+' →</a>':'<a href="./">回到学习地图 →</a>')+'</nav>';
 await writeFile(join(out,lesson.id+'.html'),page(lesson.title,body,lesson.id));
 markdown+='## '+String(lesson.order).padStart(2,'0')+' · '+lesson.title+'\n\n'+lesson.question+'\n\n目标：'+lesson.goals.join('；')+'。\n\n'+lesson.concepts.map(c=>'### '+c.title+'\n\n'+c.body+'\n').join('\n')+'\n例子：'+lesson.example+'\n\n边界：'+lesson.limit+'\n\n'+(c?c.sections.slice(1).map((s,i)=>'### '+sectionGuides[i].title+'\n\n'+sectionGuides[i].body+'\n\n原文状态：'+s.status+'；[原文]('+sourceLink('src/'+lesson.id+'.rst',s.line)+')\n').join('\n'):'')+'\n自检：'+lesson.quiz.question+'\n\n参考思路：'+lesson.quiz.answer+'\n\n';
}
markdown+='## 全部术语\n\n'+inventory.terms.map(t=>'- **'+t.term+'**：'+terms.find(x=>x.term===t.term).guide+' [原文]('+sourceLink('src/glossary.rst',t.line)+')').join('\n')+'\n\n## 参考文献索引\n\n'+inventory.references.map(r=>'- ['+r.key+']('+sourceLink('src/Crypto101.bib',r.line)+')').join('\n')+'\n';
await writeFile(join(out,'study-guide.md'),markdown);
const gaps=inventory.chapters.flatMap(c=>c.sections.filter(s=>s.status!=='原文有讲解'&&s.status!=='章节入口').map(s=>'<tr><td><a href="./'+c.id+'.html#topic-'+s.line+'">'+esc(lessons.find(l=>l.id===c.id).title)+'</a></td><td>'+esc(s.title)+'</td><td>'+esc(s.status)+'</td><td><a href="'+sourceLink('src/'+c.id+'.rst',s.line)+'">L'+s.line+'</a></td></tr>')).join('');
const sources='<p class="eyebrow">来源与边界</p><h1>知道自己读到了什么，也知道还缺什么。</h1><p class="lead">这是 Crypto 101 的中文学习导读。保留原书全部标题入口与固定来源，额外提供目标、例子、自检和学习记录。</p><section><h2>覆盖范围</h2><ul><li>原书 17 份章节、附录、术语与参考入口文件，共 '+totalHeadings+' 个标题；顶级标题对应单元，其余 187 个细节均有中文学习说明。</li><li>另有书稿工程单元，共 18 个学习单元、18 道自检题。</li><li>术语表 '+terms.length+' 个入口（含缩写与同义词），参考文件 '+inventory.references.length+' 条记录。</li><li>'+todoSections+' 个标题下检测到 TODO；下方还列出只有标题或引用的内容。自动检测不能证明没有其他遗漏。</li></ul></section><section><h2>固定研究版本</h2><p><a class="source" href="https://github.com/crypto101/book/tree/'+sha+'">'+sha+'</a>，2023-08-10。研究日期：2026-09-10。作者：Laurens Van Houtven 及贡献者。<a href="'+upstream+'LICENSE">CC BY-NC 4.0</a>。</p><p>中文导读与练习是本研究新增内容，未复制完整书稿或上游插图。许可涉及上游材料时应遵循其署名与非商业条款。</p></section><section><h2>已做和未做的验证</h2><ul><li>已核对固定版本的完整标题、术语和书目索引，检查每个细节入口都有中文说明与来源。</li><li>本站使用独立静态构建，检查页面、资源、章节路径以及进度与教学演算逻辑；详细记录见研究笔记。</li><li>未运行上游 Sphinx/LaTeX 电子书构建、密码学攻击或协议实验，未逐篇复现参考论文。</li><li>历史安全评价、系统配置、算法性能及许可状态不直接视为当前结论；需要时再查相应最新规范。</li><li>进度为个人自评。本站没有在线 AI 导师或云端笔记服务，复制引导语后可回到对话继续。</li></ul><div class="actions"><a href="./data/source-inventory.json" download>下载来源目录</a><a href="./study-guide.md" download>下载完整导读</a><a href="./notes/02-sources-and-verification.md" download>下载验证记录</a><a href="'+repo+'">研究目录</a></div></section><section><h2>需要补充或深入核查的内容</h2><div class="table-wrap"><table><thead><tr><th>单元</th><th>原始标题</th><th>状态</th><th>来源</th></tr></thead><tbody>'+gaps+'</tbody></table></div></section>';
await writeFile(join(out,'sources.html'),page('来源与范围',sources));
console.log('Crypto 101 built: 20 pages, 18 guided units, 204 source headings, 187 section guides, 57 terms, 47 references.');
