export function createKnowledgeRenderer(data, lessons, esc) {
  const points=data.points, groups=[...new Set(points.map(p=>p.group))];
  const titles=new Map(lessons.map(l=>[l.id,l.title]));
  const required=points.filter(p=>p.priority==='必会').length;
  const metadata=points.map(({id,title,priority,origin,chapter,group})=>({id,title,priority,origin,chapter,group}));
  const catalog='<script type="application/json" id="knowledge-catalog">'+JSON.stringify(metadata).replaceAll('<','\\u003c')+'</script>';
  function card(p,home) {
    return '<article class="checkpoint" id="key-'+p.id+'" data-knowledge-card="'+p.id+'"><div class="checkpoint-heading"><h3><span class="point-id">'+p.id.toUpperCase()+'</span> '+esc(p.title)+'</h3><label class="point-state">我的掌握情况<select data-knowledge-state="'+p.id+'" aria-label="'+esc(p.title)+'的掌握情况" disabled><option value="todo">未学</option><option value="review">需复习</option><option value="ready">能解释</option></select></label></div><p class="point-meta"><span class="badge">'+esc(p.priority)+'</span><span class="badge'+(p.origin==='补充学习'?' warn':'')+'">'+esc(p.origin)+'</span></p><p><strong>核心结论：</strong>'+esc(p.core)+'</p><p class="pitfall"><strong>容易漏掉或混淆：</strong>'+esc(p.pitfall)+'</p><p class="mastery"><strong>掌握标准：</strong>'+esc(p.mastery)+'</p><details class="point-question"><summary>检查自己：'+esc(p.question)+'</summary><p>'+esc(p.answer)+'</p></details><p class="source small">'+p.sources.map(s=>'<a href="'+esc(s.url)+'">'+esc(s.title)+' ↗</a>').join(' · ')+' · '+(home?'<a href="./'+p.chapter+'.html#essentials">回到「'+esc(titles.get(p.chapter))+'」</a>':'<a href="./knowledge.html#key-'+p.id+'">在总清单定位</a>')+'</p></article>';
  }
  const toolbar='<div class="knowledge-controls"><label>学习范围<select data-knowledge-filter disabled><option value="all">全部知识点</option><option value="required">先看必会</option><option value="advanced">进阶理解</option><option value="supplement">补充学习</option></select></label><label class="inline-check"><input type="checkbox" data-knowledge-pending disabled>只看未学或需复习</label></div><p data-knowledge-summary class="knowledge-summary" role="status">共 '+points.length+' 个知识点；启用 JavaScript 可记录个人状态。</p><p data-knowledge-storage class="small muted" role="status">“能解释”是个人自评；读过章节不会自动勾选知识点。</p>';
  const map='<nav class="knowledge-group-nav" aria-label="知识领域">'+groups.map((g,i)=>'<a href="#domain-'+i+'">'+esc(g)+'</a>').join('')+'</nav>';
  const scenarios=[
    ['下载一个有摘要和签名的文件',['k18','k27','k35'],'能区分摘要一致、签名有效、公钥可信，不能由此保证软件没有漏洞。'],
    ['接收一条付款请求',['k20','k21','k44','k45','k47'],'分别解释认证、防重放、对象授权与无歧义编码，说明它们不能相互替代。'],
    ['设计用户密码存储',['k15','k16','k30','k48'],'说明离线猜测、盐、派生成本与升级流程，给未实测的参数留下验证任务。'],
    ['建立到预期服务的连接',['k23','k24','k35','k36','k49','k50'],'把密钥交换、身份绑定、前向保密与早期数据条件串起来，识别协议变体。'],
    ['长期运行的加密存储服务',['k13','k21','k46','k52'],'解释消息认证、密钥生命周期，以及重启或多个发送者下的 nonce 唯一性。']
  ];
  const scenarioHtml='<section><h2>用五个场景检查能否串起来</h2><p>单个名词会解释后，再回答整个场景；这一步能发现章节之间的遗漏。</p><div class="table-wrap"><table><thead><tr><th>场景</th><th>关联知识点</th><th>验收目标</th></tr></thead><tbody>'+scenarios.map(([title,ids,goal])=>'<tr><td>'+esc(title)+'</td><td>'+ids.map(id=>'<a href="#key-'+id+'">'+id.toUpperCase()+'</a>').join('、')+'</td><td>'+esc(goal)+'</td></tr>').join('')+'</tbody></table></div></section>';
  const reviews='<section class="review-plan"><h2>以后怎样用它复习</h2><ol><li>第一次先过“必会”，不熟悉的标为“未学”。</li><li>能解释结论、前提、反例，并回答检查题后，再标“能解释”。</li><li>遇到相似概念混淆，改回“需复习”；回到对应章节补齐。</li><li>完成一组后换个场景复述。目录覆盖不等于理解深度，进阶和补学仍需继续。</li></ol><p>进度保存在当前浏览器，清理数据后会丢失。可以导出复习记录，留作以后对照；导出文件不自动恢复网站进度。</p><button type="button" class="secondary" data-knowledge-export disabled>导出复习记录</button><label for="review-prompt">把漏项带回对话，让助手逐个带你补学</label><textarea class="guide-prompt" id="review-prompt" data-review-prompt readonly>请按 Crypto 101 关键知识清单，从尚未理解的必会知识点开始。每次只讲一个点，解释前提、给反例并问我一道题，等我回答后再继续。</textarea><button type="button" class="secondary" data-review-copy disabled>复制当前待学清单与引导语</button></section>';
  const home='<p class="eyebrow">关键知识检查表</p><h1>以后复习，先检查有没有漏项。</h1><p class="lead">'+points.length+' 个关键点，分成 '+required+' 个必会与 '+(points.length-required)+' 个进阶。每一点都写清结论、误区、掌握标准与检查题；其中 '+points.filter(p=>p.origin==='补充学习').length+' 项用 RFC 或 OWASP 补充原书的空白与工程问题。</p><p class="notice">'+esc(data.scope)+' 原书标题已完整索引，关键点是按应用学习目标精选整理，不能把“全部打勾”当成已掌握整个密码学领域。</p>'+toolbar+map+'<div class="knowledge-list">'+groups.map((g,i)=>'<section id="domain-'+i+'" class="knowledge-domain"><h2>'+esc(g)+'</h2>'+points.filter(p=>p.group===g).map(p=>card(p,true)).join('')+'</section>').join('')+'</div><p data-knowledge-empty class="panel" hidden>当前筛选下没有待显示的知识点。可取消筛选检查其他领域；这不代表已经掌握清单之外的知识。</p>'+scenarioHtml+reviews+'<noscript><p class="notice">JavaScript 未启用，仍可阅读全部清单与答案；筛选、保存、复制与导出不可用。可下载完整清单自行记录。</p></noscript><div class="actions"><a href="./key-knowledge.md" download>下载完整知识清单</a><a href="./sources.html">查看原书缺口与来源</a><a href="./">回到学习地图</a></div>';
  function chapter(id) {
    const local=points.filter(p=>p.chapter===id);
    if(!local.length)return '<section id="essentials" class="goals"><h2>把这章用作查阅工具</h2><p>术语和文献用于支持理解。请用<a href="./knowledge.html">关键知识清单</a>检查核心概念，再回到这里查证。</p></section>';
    return '<section id="essentials"><h2>本章不可漏掉的关键点</h2><p>'+local.length+' 个检查点。先看结论和掌握标准；原书提炼与外部补学分别标记。章节的“完成”标记不会自动改变这些状态。</p><p data-knowledge-summary class="knowledge-summary" role="status">启用 JavaScript 可记录本章各点的掌握情况。</p><p data-knowledge-storage class="small muted" role="status"></p>'+local.map(p=>card(p,false)).join('')+'<p><a href="./knowledge.html">检查全部 '+points.length+' 个关键知识点 →</a></p></section>';
  }
  const sourceSummary='<section id="knowledge-sources"><h2>关键知识清单的补充范围</h2><p>新增 '+points.length+' 项检查点，其中 '+points.filter(p=>p.origin==='原书提炼').length+' 项依据固定书稿提炼，'+points.filter(p=>p.origin==='补充学习').length+' 项补充应用中的知识缺口。每项有来源；内容是学习提示，不是完整教程或部署参数。外部来源核对日期：'+esc(data.reviewed)+'。</p><ul>'+points.filter(p=>p.origin==='补充学习').map(p=>'<li><a href="./knowledge.html#key-'+p.id+'">'+esc(p.title)+'</a>：'+p.sources.map(s=>'<a href="'+esc(s.url)+'">'+esc(s.title)+'</a>').join('、')+'</li>').join('')+'</ul><p><a href="./knowledge.html">打开清单</a> · <a href="./key-knowledge.md" download>下载清单</a></p></section>';
  const markdown='# Crypto 101 关键知识检查表\n\n'+data.scope+'\n\n核对日期：'+data.reviewed+'。必会 '+required+' 项，进阶 '+(points.length-required)+' 项。每项应能解释结论、前提与反例；个人勾选不是自动验收。\n\n'+groups.map(g=>'## '+g+'\n\n'+points.filter(p=>p.group===g).map(p=>'### '+p.id.toUpperCase()+' · '+p.title+'\n\n'+p.priority+' · '+p.origin+'\n\n- [ ] 能解释以下知识点（自评）\n\n**核心结论：** '+p.core+'\n\n**常见误区：** '+p.pitfall+'\n\n**掌握标准：** '+p.mastery+'\n\n**检查题：** '+p.question+'\n\n**参考思路：** '+p.answer+'\n\n来源：'+p.sources.map(s=>'['+s.title+']('+s.url+')').join(' · ')+'\n').join('\n')).join('\n');
  return {catalog,home,chapter,sourceSummary,markdown};
}
